/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/layout/AppBar.vue')['default']
    AppDrawer: typeof import('./components/layout/AppDrawer.vue')['default']
    AppDrawerItem: typeof import('./components/layout/AppDrawerItem.vue')['default']
    AppNotification: typeof import('./components/layout/AppNotification.vue')['default']
    AppNotificationItem: typeof import('./components/layout/AppNotificationItem.vue')['default']
    ChartBar: typeof import('./components/demo-charts/ChartBar.vue')['default']
    ChartLine: typeof import('./components/demo-charts/ChartLine.vue')['default']
    ChartPie: typeof import('./components/demo-charts/ChartPie.vue')['default']
    ChartRadar: typeof import('./components/demo-charts/ChartRadar.vue')['default']
    DndSave: typeof import('./components/dnd-save.vue')['default']
    DndStat: typeof import('./components/dnd-stat.vue')['default']
    DndStats: typeof import('./components/dnd-stats.vue')['default']
    Fraction: typeof import('./components/fraction.vue')['default']
    RouterWrapper: typeof import('./components/layout/RouterWrapper.vue')['default']
    Stat: typeof import('./components/Stat.vue')['default']
    StatsCard: typeof import('./components/StatsCard.vue')['default']
    VPage: typeof import('./components/VPage.vue')['default']
  }
}
